jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "60"
          NEXT_PUBLIC_MATOMO_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_API_URL: https://backoffice-les1000jours.fabrique.social.gouv.fr
          NEXT_PUBLIC_PASTEK_CHAT_ID: "1"
          NEXT_PUBLIC_TEST_NUMBER_ENABLED: "false"
          NEXT_PUBLIC_LANDING_PAGE_BLUES_RESOURCES: "https://1000jours-blues.fabrique.social.gouv.fr/ressources"
          NEXT_PUBLIC_CALENDLY_LINK: https://calendly.com/rdv-nos1000jours/30min