global:
  imageProject: 1000jours

app:
  ~chart: app
  imagePackage: app
  probesPath: /healthz
  containerPort: 3000
  envFrom: 
    - configMapRef:
        name: nos1000jours-blues-epds-widget-configmap
