global:
  imageProject: 1000jours

app:
  probesPath: /healthz
  containerPort: 3000
  envFrom: 
    - configMapRef:
        name: nos1000jours-blues-epds-widget-configmap

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "74"
          NEXT_PUBLIC_MATOMO_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_PASTEK_CHAT_ID: "2"
          NEXT_PUBLIC_TEST_NUMBER_ENABLED: "true"
          NEXT_PUBLIC_LANDING_PAGE_BLUES_RESOURCES: https://1000jours-blues-preprod.ovh.fabrique.social.gouv.fr/ressources
          NEXT_PUBLIC_CALENDLY_LINK: https://calendly.com/test1000jfabnum/30min
          # NEXT_PUBLIC_API_URL:
