name: Tests

on:
  pull_request:
    branches:
        - '**'

jobs:

  ##############################################################################
  ## TEST APPLICATION
  ##############################################################################
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline

    - name: Run tests
      run: yarn test --coverage