name: Tests

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: |
          yarn test